version: '3.4'

services:
  db:
     image: postgres
     restart: always
     ports:
       - 5432:5432
     environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: admin
     volumes:
       - charity1:/var/lib/postgresql/data
     networks:
       - network1
 
  charityaspcore5:
     image: charity1
     ports:
       - 5005:80
     build: .
     links:
       - db
     depends_on:
       - "db"
     networks:
       - network1
 
volumes:
  charity1:
 
networks:
  network1:
     driver: bridge